name: autogluon
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - autogluon
  - rdkit
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - scipy
  - xgboost
